### ISSUE TITLE
Adding Chance to get Caught

### ISSUE THREAD

**Issue by jfrank1120** [pitt-cdm/twine--summer-nights-1#2]
Each passage needs to have code added to implement the possibility of getting caught by the seeker. Thus ending the game if the hider is caught

**Comment by benmiller314** [comment]
You can add a special footer passage, which will then get invisibly appended to every other passage. See documentation for [Harlowe](https://twine2.neocities.org/#passagetag_header) or [SugarCube](http://www.motoslave.net/sugarcube/2/docs/#special-names).

**Comment by jfrank1120** [comment]
Ended up not implementing this feature due to time constraints and focusing on the story line instead
