### ISSUE TITLE
Changing From Hider to Hider

### ISSUE THREAD

**Issue by jfrank1120** [pitt-cdm/twine--summer-nights-1#3]
When a hider ends up in the same location as another hider. They should be offered the option to change and take control of them, thus allowing them to follow their path.

**Comment by benmiller314** [comment]
Since only one person is playing at a time, how will you decide where the other hiders are? Will you randomly initialize them at the start of gameplay (or, rather, right after the player makes a choice of character)?

**Comment by jfrank1120** [comment]
Was able to fully implement this feature to the game so that you can change characters
